# <font color='#eb3483'> NumPy Exercises </font>

NumPy is a really handy package to have mastered - these bonus questions are your chance to practice and get the functions engrained. Remember that learning data science is like learning a sport - you'll only get better with time and practice! You can start by importing NumPy below:

### <font color='#eb3483'>  1. Creating Arrays </font>
For this question we're going to be creating the following array two different ways
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
(a) Start by creating a list with the data and turning it into a NumPy array - call it array

In [10]:
import numpy as np
array = np.array([[1, 6, 11],
                [2, 7, 12],
                [3, 8, 13],
                [4, 9, 14],
                [5, 10, 15]])
print(array)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


(b) **Challenge!** Create the same array, but instead of typing in each value manually into a list generate the matrix using `np.arange`. Hint: Arange creates a vector, you'll need to use reshape and transpose to get the final result

In [76]:
array = np.arange(1, 16)
print(array, "\n")
array = array.reshape(3,5)
print(array, "\n")
array = array.T
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### <font color='#eb3483'>  2. Array Attributes and Indexing </font>


Now let's delve a little deeper to understand `array`

What's the shape of the array?

In [17]:
print(array.shape)

(5, 3)


What's the type of the array?

In [19]:
print(array.dtype)

int32


Set the type of array to float (hint: the dtype for float in NumPy is np.float64)

In [23]:
array.astype(np.float64)

array([[ 1.,  6., 11.],
       [ 2.,  7., 12.],
       [ 3.,  8., 13.],
       [ 4.,  9., 14.],
       [ 5., 10., 15.]])

Select the 3rd column of the array

In [26]:
print(array[2])

[ 3  8 13]


Select the (0,1), (2, 2) and (4,0) elements of the array at the same time

In [32]:
row = [0, 2, 4]
col = [1, 2, 0]
array[row, col]

array([ 6, 13,  5])

Slice into the array to get the top 2x2 square of data (i.e. the first two columns of the first two rows)

In [80]:
print(array[:2, :2])

[[1 6]
 [2 7]]


**Challenge!** Select all values of array that are divisible by 2 (hint you might want to use the `%` (integer division) operator)

In [29]:
array[array%2 == 0]

array([ 6,  2, 12,  8,  4, 14, 10])

### <font color='#eb3483'>  3. Growing our array </font>


Now let's start changing our array!

Create a vector with the numbres 16 to 20, call it newCol *(hint: use np.arange)*

In [83]:
newCol = np.arange(16, 21)
print(newCol)

[16 17 18 19 20]
(5,)


Reverse newCol (i.e. 20 19 18...etc)

In [85]:
newCol = newCol[::-1]
print(newCol)

[16 17 18 19 20]


Assign the value `100` to the 2nd position in newCol

In [86]:
newCol[1] = 100
print(newCol)

[ 16 100  18  19  20]


Reshape newCol to have dimension (5,1) instead of just (5,)

In [88]:
print(newCol.shape)
newCol = newCol.reshape(5,1)
print(newCol.shape)

(5,)
(5, 1)


Add the new column to our array (hint: you should use either vstack or hstack, which one makes sense?)

In [89]:
np.hstack((array, newCol))

array([[  1,   6,  11,  16],
       [  2,   7,  12, 100],
       [  3,   8,  13,  18],
       [  4,   9,  14,  19],
       [  5,  10,  15,  20]])

### <font color='#eb3483'>  4. Aggregations </font>
Now let's build some aggregations of our array:

Get the average value in our matrix

In [45]:
print(np.mean(array))

8.0


Now get the average for each column

In [69]:
print(np.mean(array, axis = 0))

[ 3.  8. 13.]


Get the standard deviation of our matrix

In [59]:
print(np.std(array))

4.320493798938574


**Challenge!** Get the maximum value in the array, but only include values that are less than the average value of the matrix

In [67]:
array = np.arange(1, 16).reshape(3, 5).T
print(array)
mean = np.mean(array)
print(mean)
less = array[array < mean]
print(less)
max = np.max(less)
print(max)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
8.0
[1 6 2 7 3 4 5]
7
